# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abids', '0005_competitor_bid_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
