# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abids', '0007_competitor_bid_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='bid_comment',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
    ]
